#HYDRAD Build SConscript
#Will Barnes
#15 December 2015

#Import needed modules
import glob

#Import environment from SConstruct
Import('env')

sources = glob.glob('*.cpp')

ot_sources = glob.glob('OpticallyThick/*.cpp')

objs = env.Object(sources+ot_sources)

Return('objs')